#axis:
cmd_x: 1
cmd_y: 4
cmd_z: 0
cmd_joint: 1
cmd_gripper_rot: 7
cmd_gripper_grip: 6

#buttons
cmd_a_positive: 10
cmd_a_negative: 9
crawler: 0
enable: 4
fast: 5
joint_increase: 1
joint_decrease: 2
control_mode_toggle: 3
